---
  # Ejecutarlos en el grupo racknerd
- hosts: racknerd
  # Become sudo
  become: yes
  # Tasks
  tasks:

  - name: Update repositories
    command: apt update

  - name: Install packages
    apt:
      name:
      - apache2
      - php-fpm
      - mysql-server
      - php7.4-mysqli
      - libapache2-mod-php7.4
      - python3-pip
      state: latest
      
  # Optional check if MySQL its running
  #- name: Check MySQL service
  #  service:
  #    name: mysqld
  #    state: started
  #    enabled: True

  - name: Set MySQL "root" pass
    mysql_user:
      login_host: 'localhost'
      login_user: 'root'
      login_password: '' # Without password, by defaul "root" user doesnt have it
      name: 'root'
      password: 'CHANGE_ME'
      state: present

  - name: Create database "wordpress"
    community.mysql.mysql_db:
      login_user: root
      login_password: CHANGE_ME
      name: wordpress
      encoding: utf8
      state: present
      
  - name: Create user "wordpress" with permis in BBDD "wordpress"
    community.mysql.mysql_user:
      login_user: root
      login_password: CHANGE_ME
      state: present
      name: wordpress
      password: CHANGE_ME
      priv:
        'wordpress.*:ALL'

  # Disable mpm_event and enable mpm_prefork
  # To avoid conflict with PHP module
  - name: Disable mpm_event Apache
    command: a2dismod mpm_event

  - name: Enable mpm_prefork
    command: a2enmod mpm_prefork

  - name: Restart apache
    command: systemctl restart apache2
  
  - name: Enable Php
    command: a2enmod php7.4
  
  - name: Restart apache
    command: systemctl restart apache2
  
  - name: Download and extract Wordpress
    unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: /var/www/html
      # Download in "racknerd" server
      remote_src: yes
  
  - name: Install pymysql
    command: python3 -m pip install PyMySQL