version: "3.7"
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraftAndres
    ports:
      - 25565:25565
    volumes:
      - ./Minecraft/data:/data
    environment:
      - TYPE=CUSTOM
      - CUSTOM_SERVER=serverstarter-2.0.1.jar
      - EULA=TRUE
      - MEMORY=4G
  7dtdserver:
    image: vinanrra/7dtd-server
    container_name: 7dtdserver
    environment:
      - START_MODE=1 #Change between START MODES
      - VERSION=stable # Change between 7 days to die versions
      - PUID=1000 # Remember to use same as your user
      - PGID=1000 # Remember to use same as your user
      - TimeZone=Europe/Madrid
      - TEST_ALERT=YES
      - ALLOC_FIXES=YES #Optional - Install ALLOC FIXES
    volumes:
      - ./7Days/ServerFiles:/home/sdtdserver/serverfiles/ #Optional, serverfiles
      - ./7Days/7DaysToDie:/home/sdtdserver/.local/share/7DaysToDie/ #Optional, maps files
      - ./7Days/log:/home/sdtdserver/log/ #Optional, logs
      - ./7Days/backups:/home/sdtdserver/lgsm/backup/ #Optional, backups
      - ./7Days/LGSM-Config:/home/sdtdserver/lgsm/config-lgsm/sdtdserver # Optional, alerts
    ports:
      - 26900:26900/tcp
      - 26900:26900/udp
      - 26901:26901/udp
      - 26902:26902/udp
      - 8080:8080/tcp #OPTIONAL WEBADMIN
      - 8081:8081/tcp #OPTIONAL TELNET
      - 8082:8082/tcp #OPTIONAL WEBSERVER https://7dtd.illy.bz/wiki/Server%20fixes
    restart: unless-stopped #NEVER USE WITH START_MODE=4 or START_MODE=0
  portainer:
    image: portainer/portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
  db:
    image: mysql
    container_name: mySQL
    env_file:
      - ./MySQL/MySQL.env
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
  ddclient:
    image: linuxserver/ddclient
    container_name: ddclient
    env_file:
      - ./DDClient/ddclient.env
    volumes:
      - ./DDClient/config:/config
    restart: unless-stopped
  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    env_file:
      - ./Duckdns/duckdns.env
    volumes:
      - ./Duckdns/config:/config
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,grafana-worldmap-panel
    restart:
      always
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    env_file:
      - ./Gitea/Gitea.env
    volumes:
      - ./Gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      #- 3000:3000
      - 222:22
    restart: always
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ./Influxdb/config:/var/lib/influxdb
    restart:
      always
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    env_file:
      - ./Jackett/jackett.env
    volumes:
      - ./Jackett/config:/config
    #ports:
      #- 9117:9117
    restart: unless-stopped
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    env_file:
      - ./Nginx_SSL/web.env
    volumes:
      - ./Nginx_SSL/config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
  plex:
    image: linuxserver/plex
    container_name: plex
    env_file:
      - ./Plex/Plex.env
    volumes:
      - ./Plex/config:/config
      - /media/storage/home/vinanrra/Docker/Plex/tv:/tv
      - /media/storage/home/vinanrra/Docker/Plex/peliculas:/movies
      - /media/storage/home/vinanrra/Docker/Plex/transcode:/transcode
      - /media/storage:/anime
    restart: unless-stopped
    network_mode: host
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    env_file:
      - ./Radarr/Radarr.env
    volumes:
      - ./Radarr/config:/config
      - /media/storage/home/vinanrra/Docker/Plex/descargas:/downloads/descargas
      - /media/storage/home/vinanrra/Docker/Plex/tv:/tv
      - /media/storage/home/vinanrra/Docker/Plex/peliculas:/movies
      - /media/storage:/downloads/2TB
      - /media/storage/home/vinanrra/Docker/Plex:/downloads
    #ports:
      #- 7878:7878
    restart: unless-stopped
  rclone:
    image: pfidr/rclone
    container_name: rclone
    env_file:
      - ./Rclone/Rclone.env
    volumes:
      - ./Rclone/config:/config
      - ./Rclone/logs:/logs
      - /media/storage/home/vinanrra/Backups:/source
    restart: unless-stopped
  rutorrent:
    image: linuxserver/rutorrent:v3.9-ls70
    container_name: rutorrent
    env_file:
      - ./rutorrent/rutorrent.env
    volumes:
      - ./rutorrent/config:/config
      - /media/storage/home/vinanrra/Docker/Plex/tv:/downloads/tv
      - /media/storage/home/vinanrra/Docker/Plex/peliculas:/downloads/peliculas
      - /media/storage/Plex/Anime:/downloads/Anime
      - /media/storage/home/vinanrra/Docker/Plex/descargas:/downloads/descargas
      - /media/storage/home/vinanrra/Docker/Plex/ratio:/downloads/ratio
    ports:
      - 9080:80
      - 5000:5000
      - 51413:51413
      - 6881:6881/udp
    restart: unless-stopped
  smartmontools:
    image: mdhiggins/smartmontools
    container_name: smartmontools
    privileged: true
    volumes:
      - ./smartmontools/smartd.conf:/etc/smartd.conf
      - ./smartmontools/ssmtp:/etc/ssmtp
    restart: always
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    env_file:
      - ./Sonarr/Sonarr.env
    volumes:
      - ./Sonarr/config:/config
      - /media/storage/home/vinanrra/Docker/Plex/descargas:/downloads/descargas
      - /media/storage/home/vinanrra/Docker/Plex/tv:/downloads/tv
      - /media/storage/home/vinanrra/Docker/Plex/peliculas:/downloads/peliculas
      - /media/storage:/downloads/2TB
    #ports:
      #- 8989:8989
    restart: unless-stopped
  speedtest:
    image: barrycarey/speedtest-for-influxdb-and-grafana
    container_name: speedtest
    volumes:
      - ./SpeedTest/config.ini:/src/config.ini
    restart: always
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    env_file:
      - ./Tautulli/Tautulli.env
    volumes:
      - ./Tautulli/config:/config
      - ./Tautulli/config/logs:/logs
    #ports:
    #  - 8181:8181
    restart: unless-stopped
  varken:
    hostname: varken
    container_name: varken
    image: boerderij/varken
    volumes:
      - ./Varken/config:/config
    env_file:
      - ./Varken/Varken.env
    depends_on:
      - influxdb
    restart: unless-stopped
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./Nextcloud/config:/config
      - ./Nextcloud/data:/data
    restart: unless-stopped
  valheim:
    container_name: valheim-server
    image: lloesche/valheim-server
    environment:
      - SERVER_NAME=Zuperbicion
      - WORLD_NAME=Dockerized
      - SERVER_PASS=eresTonto
      - SERVER_PUBLIC=false
      - VALHEIM_PLUS=false
      - TZ=Europe/Madrid
    volumes:
      - ./Valheim/config:/config
      - ./Valheim/data:/opt/valheim
    ports:
      - 2456-2458:2456-2458/udp
    restart: unless-stopped
  traefik:
    image: "traefik:v2.2"
    container_name: Traefik
    # Fuente: https://blog.creekorful.com/2020/01/how-to-expose-traefik-2-dashboard-securely-docker-swarm/
    command:
      # Habilita la API
      - "--api=true"
      # Habilita el panel de control
      - "--api.dashboard=true"
      # Le decimos a Traefik que usamos Docker
      - "--providers.docker=true"
      # Los contenedores sin la label "traefik.enable=true" los ignora
      - "--providers.docker.exposedbydefault=false"
      # Puertos
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      ## Redireccion HTTP a HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      ## Redireccion HTTP a HTTPS
      ## Certificados SSL
      # Use the HTTP-01 challenge to generate and renew ACME certificates by provisioning an HTTP resource under a well-known URI.
      - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge=true"
      # Tipo de verificacion
      - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge.entrypoint=web"
      # Correo asociado
      - "--certificatesresolvers.letsencryptresolver.acme.email=XXX@XXX.com"
      # Donde guardarlo
      - "--certificatesresolvers.letsencryptresolver.acme.storage=/letsencrypt/acme.json"
      ## Certificados SSL
    labels:
      # Activamos la deteccion
      - "traefik.enable=true"
      # Ruta de acceso al panel
      - "traefik.http.routers.traefik.rule=Host(`traefik.XXX.XX`)"
      # Nombre de la entrada, debe concidir con "--entrypoints.websecure.address=:443"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      # Nombre del generador de SSL que usaremos, debe coincidir con "--certificatesresolvers.letsencryptresolver...""
      - "traefik.http.routers.traefik.tls.certresolver=letsencryptresolver"
      # Al activar la API con "--api=true", se genera un servicio llamado "api@internal" y debe ser referenciado en la ruta
      - "traefik.http.routers.traefik.service=api@internal"
      # Nombre del middlewares, puede ser cualquiera
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      # Usuarios, el nombre de "traefik.http.middlewares.[NOMBRE]..." debe ser igual al middleware creado
      - "traefik.http.middlewares.traefik-auth.basicauth.users=XXX:XXXX."
      # Especificamos la red a usar, para evitar problemas de enrutamiento
      # Without that flag traefik would randomly choose a network (usually the wrong one).
      - "traefik.docker.network=frontend"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Carpeta de certificados
      - "./Traefik/Data/Letsencrypt:/letsencrypt"
      # Socket Docker
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks: 
      - frontend
  mysql:
    image: mysql
    container_name: Mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=XXXX
    #ports:
      #- 3306:3306
    networks:
      - backend
  wordpress:
    image: wordpress
    container_name: Wordpress
    depends_on: 
      - mysql
    labels:
      # Ruta por la cual se entrara al contenedor, traefik al leer esa web, desviara a Wordpress
      - traefik.http.routers.wordpress.rule=Host(`XXXX.XXX`)
      # Tipo de entrada, en este caso HTTPS, llamada para nosotros "websecure"
      - traefik.http.routers.wordpress.entrypoints=websecure
      # Nuestro generador de certificados TLS, en este caso llamada para nosotros "letsencryptresolver"
      - traefik.http.routers.wordpress.tls.certresolver=letsencryptresolver
      # Activaremos la deteccion de Traefik
      - traefik.enable=true
      # Puerto que usa nuestro contenedor, por el cual Traefik se conectara, se debe especificar para poder conectarse
      - traefik.port=80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: XXXXX
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./Wordpress/Data/Html:/var/www/html
    networks: 
     - frontend
     - backend
networks:
  frontend:
  backend:
volumes:
  portainer_data:
